#
# Makefile for the misc classes
#

EXTRA_CFLAGS += -D__IN_XENOMAI__ -Iinclude/xenomai 
obj-$(CONFIG_GPIOCLASS_RTDM)	+= gpio_rtdm.o
obj-$(CONFIG_PWMCLASS_RTDM)	+= pwm_rtdm.o
obj-$(CONFIG_SPICLASS_RTDM)	+= spi_rtdm.o
obj-$(CONFIG_RT_SPI_ATMEL)	+= atmel_rt_spi.o
obj-$(CONFIG_AD7766_RTDM)	+= ad7766_rtdm.o
obj-$(CONFIG_FPGA_RTDM)		+= fpga_rtdm.o
