#
# Makefile for the ioex devices
#

# Each configuration option enables a list of files.

obj-$(CONFIG_ECOREEX)		+= ecoreex-core.o
obj-$(CONFIG_ECOREEX_EVC)	+= ecoreex-evc.o
obj-$(CONFIG_ECOREEX_HWMS)	+= ecoreex-hwms.o
obj-$(CONFIG_ECOREEX_SDAC)	+= ecoreex-sdac.o
obj-$(CONFIG_ECOREEX_SOM150)	+= ecoreex-som150.o
obj-$(CONFIG_ECOREEX_SOM200)	+= ecoreex-som200.o
obj-$(CONFIG_BOARDSPEC)		+= boardspec.o
obj-$(CONFIG_PB1010)		+= pb1010.o
obj-$(CONFIG_PWMCLASS)		+= pwmd.o
obj-$(CONFIG_ICB_G2L_PLD) 	+= icb-g2l-pld.o
